import { createElement as h } from 'react'
import { render, screen } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'

const api = vi.hoisted(function () { return { getReactions: vi.fn() } })
vi.mock('@/lib/server/api', function () { return { getReactions: api.getReactions } })
vi.mock('@/components/app/chrome', function () { return { PageShell: function PageShell(props: any) { return h('div', { 'data-testid': 'page-shell', 'data-mode': props.mode }, [h('h1', { key: 'title' }, props.title), h('div', { key: 'body' }, props.children) ]) }, Panel: function Panel(props: any) { return h('section', {}, [h('h2', { key: 'title' }, props.title), h('div', { key: 'body' }, props.children) ]) }, MetricGrid: function MetricGrid(props: any) { return h('div', {}, props.items.map(function (item: any) { return h('div', { key: item.label }, item.label + ' ' + item.value) })) }, Badge: function Badge(props: any) { return h('span', {}, props.children) }, ScoreBar: function ScoreBar(props: any) { return h('span', {}, String(Math.round(props.value || 0))) }, DataTable: function DataTable(props: any) { return h('table', {}, [h('thead', { key: 'head' }, h('tr', {}, props.headers.map(function (header: string, index: number) { return h('th', { key: header + String(index) }, header) }))), h('tbody', { key: 'body' }, (props.rows || []).map(function (row: any[], rowIndex: number) { return h('tr', { key: rowIndex }, row.map(function (cell: any, cellIndex: number) { return h('td', { key: String(rowIndex) + '-' + String(cellIndex) }, cell) })) })) ]) } } })
import LiveReactionsPage from '@/app/app/live-reactions/page'

const payload = { filters: { family: 'CPI', asset: 'SPX', country: 'United States', currency: 'USD' }, familyOptions: ['CPI', 'NFP'], assetOptions: ['SPX', 'US10Y'], summary: { sampleSize: 3, directionDistribution: { positive: 2, negative: 1, flat: 0 }, windowStats: [{ window: '1d', sampleSize: 3, meanMovePct: 0.42, medianMovePct: 0.39, positiveHitRate: 0.67, negativeHitRate: 0.33 }, { window: '5d', sampleSize: 3, meanMovePct: 0.88, medianMovePct: 0.82, positiveHitRate: 0.67, negativeHitRate: 0.33 }], note: 'Only windows supportable by the available market resolution are included.', freshness: { label: 'Reactions', source: 'FRED public series', freshness: 'degraded', mode: 'fallback', note: 'Fallback history' } }, records: [{ eventId: 'event-cpi-mar', title: 'US CPI', family: 'CPI', scheduledAt: '2026-04-25T12:30:00+00:00', country: 'United States', currency: 'USD', href: '/app/events/event-cpi-mar', windows: { '1d': 0.5, '5d': 0.9 } }], calendar: { mode: 'demo', freshness: 'degraded', note: 'Seeded calendar fallback is being served because the live provider is unavailable.' } }

describe('LiveReactionsPage', function () { it('renders reaction metadata with explicit fallback honesty', async function () { api.getReactions.mockResolvedValue(payload) ; const view = await LiveReactionsPage({ searchParams: Promise.resolve({ family: 'CPI', asset: 'SPX', country: 'United States', currency: 'USD' }) }) ; render(view) ; expect(screen.getByText('Window summary')).toBeInTheDocument() ; expect(screen.getByText('Reaction tape')).toBeInTheDocument() ; expect(screen.getByText('Integrity notes')).toBeInTheDocument() ; expect(screen.getByText('Only windows supportable by the available market resolution are included.')).toBeInTheDocument() ; expect(screen.getByText('demo')).toBeInTheDocument() ; expect(screen.getByTestId('page-shell')).toHaveAttribute('data-mode', 'mixed') ; expect(screen.getByRole('link', { name: 'US CPI' })).toHaveAttribute('href', '/app/events/event-cpi-mar') }) })
