import { createElement as h } from 'react'
import { render, screen } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'

const api = vi.hoisted(function () { return { getMarketBiasInsights: vi.fn() } })
vi.mock('@/lib/server/api', function () { return { getMarketBiasInsights: api.getMarketBiasInsights } })
vi.mock('@/components/app/chrome', function () { return { PageShell: function PageShell(props: any) { return h('div', {}, [h('h1', { key: 'title' }, props.title), h('div', { key: 'body' }, props.children) ]) }, Panel: function Panel(props: any) { return h('section', {}, [h('h2', { key: 'title' }, props.title), h('div', { key: 'body' }, props.children) ]) }, MetricGrid: function MetricGrid(props: any) { return h('div', {}, props.items.map(function (item: any) { return h('div', { key: item.label }, item.label + ' ' + item.value) })) }, Badge: function Badge(props: any) { return h('span', {}, props.children) }, DataTable: function DataTable(props: any) { return h('table', {}, [h('thead', { key: 'head' }, h('tr', {}, props.headers.map(function (header: string, index: number) { return h('th', { key: header + String(index) }, header) }))), h('tbody', { key: 'body' }, (props.rows || []).map(function (row: any[], rowIndex: number) { return h('tr', { key: rowIndex }, row.map(function (cell: any, cellIndex: number) { return h('td', { key: String(rowIndex) + '-' + String(cellIndex) }, cell) })) })) ]) } } })
import MarketBiasPage from '@/app/app/market-bias/page'

const payload = { summary: { label: 'Supportive', score: 58.4, confidence: 0.72, note: 'Bias is derived from factor contributions and live market behavior, not decorative labels.', freshness: { label: 'Bias', source: 'Composite', freshness: 'fresh', mode: 'live', note: 'Composite factor stack' } }, factors: [{ key: 'liquidity', label: 'Liquidity', score: 62.1, direction: 'Supportive', strength: 62.1, confidence: 0.74, detail: 'Balance sheet and reserves are stabilizing.', note: 'Liquidity backdrop is supportive for risk assets.', source: { label: 'Liquidity', source: 'FRED', freshness: 'fresh', mode: 'live', note: 'FRED factor' } }], assets: [{ symbol: 'SPX', name: 'SPX Index', direction: 'Bullish', score: 63.2, confidence: 0.7, change1d: 0.4, change30d: 2.1, note: 'Equities still reflect the supportive factor stack.', freshness: { label: 'SPX', source: 'FRED', freshness: 'fresh', mode: 'live', note: 'FRED market tape' } }], providerStatus: { live: 1, degraded: 0, detail: { SPX: 'live' } } }

describe('MarketBiasPage', function () { it('renders factor and asset tables with interpretable notes', async function () { api.getMarketBiasInsights.mockResolvedValue(payload) ; const view = await MarketBiasPage() ; render(view) ; expect(screen.getByText('Market Bias')).toBeInTheDocument() ; expect(screen.getByText('Factor contributions')).toBeInTheDocument() ; expect(screen.getByText('Asset influence')).toBeInTheDocument() ; expect(screen.getByText('Factor notes')).toBeInTheDocument() ; expect(screen.getByText('Liquidity backdrop is supportive for risk assets.')).toBeInTheDocument() ; expect(screen.getByText('Live assets 1')).toBeInTheDocument() }) })
