import { createElement as h } from 'react'
import { render, screen } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'

const api = vi.hoisted(function () { return { getReports: vi.fn() } })
vi.mock('@/lib/server/api', function () { return { getReports: api.getReports } })
vi.mock('@/components/app/chrome', function () { return { PageShell: function PageShell(props: any) { return h('div', { 'data-testid': 'page-shell', 'data-mode': props.mode }, [h('h1', { key: 'title' }, props.title), h('div', { key: 'body' }, props.children) ]) }, Panel: function Panel(props: any) { return h('section', {}, [h('h2', { key: 'title' }, props.title), h('div', { key: 'body' }, props.children) ]) }, MetricGrid: function MetricGrid(props: any) { return h('div', {}, props.items.map(function (item: any) { return h('div', { key: item.label }, item.label + ' ' + item.value) })) }, DataTable: function DataTable(props: any) { return h('table', {}, [h('thead', { key: 'head' }, h('tr', {}, props.headers.map(function (header: string, index: number) { return h('th', { key: header + String(index) }, header) }))), h('tbody', { key: 'body' }, (props.rows || []).map(function (row: any[], rowIndex: number) { return h('tr', { key: rowIndex }, row.map(function (cell: any, cellIndex: number) { return h('td', { key: String(rowIndex) + '-' + String(cellIndex) }, cell) })) })) ]) } } })
import ReportsPage from '@/app/app/reports/page'

const reports = [{ id: 'report-2026-w17', slug: 'weekly-2026-04-20', title: 'Weekly Macro Brief', status: 'ready', mode: 'deterministic', weekStart: '2026-04-20', weekEnd: '2026-04-26', summary: 'Deterministic weekly summary grounded in structured data.', body: { watchItems: ['US CPI', 'DXY', 'Liquidity'] }, sourceMeta: [{ label: 'Reports', source: 'Structured product layer', freshness: 'fresh', mode: 'fallback', note: 'Deterministic only' }], createdAt: '2026-04-26T08:00:00+00:00' }]

describe('ReportsPage', function () { it('renders archive, deterministic mode, and watch items', async function () { api.getReports.mockResolvedValue(reports) ; const view = await ReportsPage() ; render(view) ; expect(screen.getByText('Reports')).toBeInTheDocument() ; expect(screen.getByText('Report archive')).toBeInTheDocument() ; expect(screen.getByText('Latest briefs')).toBeInTheDocument() ; expect(screen.getByText('Deterministic weekly summary grounded in structured data.')).toBeInTheDocument() ; expect(screen.getAllByText('US CPI / DXY / Liquidity').length).toBeGreaterThan(0) ; expect(screen.getAllByText('deterministic').length).toBeGreaterThan(0) ; expect(screen.getByTestId('page-shell')).toHaveAttribute('data-mode', 'fallback') }) })
