import type { CentralBank, FeedItem, GeoEvent, GeoboardPayload, GeoboardRankingMetadata, GeoboardSourceMetadata, MacroEvent, RegimeZone, TradeRoute } from './types'

const FALLBACK_SOURCE: GeoboardSourceMetadata = {
 providerKey: 'geoboard-fallback',
 label: 'Geoboard fallback dataset',
 sourceType: 'fallback',
 sourceTier: 'secondary',
 mode: 'fallback',
 freshness: 'degraded',
 note: 'Fallback continuity layer. Signals remain visible but are not live provider events.',
 sourceUrl: null,
 fetchedAt: '2026-04-08T06:00:00+00:00',
 lastUpdated: '2026-04-08T06:00:00+00:00',
}

function rank(score: number, urgency: number, importance: number, confidence: number): GeoboardRankingMetadata {
 return {
  rankScore: score,
  urgencyScore: urgency,
  importanceScore: importance,
  confidenceScore: confidence,
  recencyScore: 0.45,
  sourceQualityScore: 0.38,
  watchlistOverlapScore: 0,
  catalystProximityScore: 0.2,
  regionSignificanceScore: 0.6,
  regimeRelevanceScore: 0.5,
  rationale: ['Fallback ranking placeholder'],
 }
}

export const FALLBACK_GEO_EVENTS: GeoEvent[] = [
 {
  id: 'geo-fallback-hormuz',
  title: 'Shipping insurers widen cover costs around Hormuz corridor',
  source: 'Fallback data',
  lat: 26.6,
  lon: 56.9,
  tone: -7.2,
  date: '2026-04-08T06:00:00+00:00',
  url: 'https://api.gdeltproject.org/',
  affectedAssets: ['OIL', 'DXY', 'XAU'],
  mode: 'fallback',
  classification: 'Shipping / Logistics',
  regionCode: 'MENA',
  regionGroup: 'Middle East',
  countryCode: 'IR',
  country: 'Iran',
  locationPrecision: 'region',
  linkedEventId: null,
  linkedEventSlug: null,
  relatedNewsClusterIds: [],
  relatedNewsIds: [],
  whyItMatters: 'Fallback risk headline for chokepoint stress continuity.',
  geoboardModes: ['STANDARD', 'RISK'],
  sourceMeta: FALLBACK_SOURCE,
  ranking: rank(0.66, 0.68, 0.74, 0.42),
 },
 {
  id: 'geo-fallback-blacksea',
  title: 'Black Sea logistics remain strained after renewed port alerts',
  source: 'Fallback data',
  lat: 45.1,
  lon: 31.3,
  tone: -6.4,
  date: '2026-04-08T05:10:00+00:00',
  url: 'https://api.gdeltproject.org/',
  affectedAssets: ['WHEAT', 'EURUSD', 'NATGAS'],
  mode: 'fallback',
  classification: 'Shipping / Logistics',
  regionCode: 'EMEA',
  regionGroup: 'Eastern Europe',
  countryCode: 'UA',
  country: 'Ukraine',
  locationPrecision: 'region',
  linkedEventId: null,
  linkedEventSlug: null,
  relatedNewsClusterIds: [],
  relatedNewsIds: [],
  whyItMatters: 'Fallback logistics risk row for grain corridor sensitivity.',
  geoboardModes: ['STANDARD', 'RISK'],
  sourceMeta: FALLBACK_SOURCE,
  ranking: rank(0.62, 0.64, 0.7, 0.4),
 },
]

export const FALLBACK_MACRO_EVENTS: MacroEvent[] = [
 {
  id: 'macro-fallback-cpi',
  name: 'US CPI',
  country: 'United States',
  countryCode: 'US',
  lat: 38.9,
  lon: -95,
  date: '2026-04-10T12:30:00+00:00',
  forecast: 2.9,
  previous: 3.1,
  impactLevel: 'High',
  expectedReaction: 'Softer core should ease front-end yields and lean risk-on.',
  relatedAssets: ['SPX', 'DXY', 'XAU'],
  mode: 'fallback',
  family: 'US CPI',
  category: 'Inflation',
  regionCode: 'NA',
  regionGroup: 'North America',
  linkedEventId: null,
  linkedEventSlug: null,
  linkedReactionPath: '/app/live-reactions?family=US%20CPI&asset=SPX',
  linkedCalendarPath: '/app/macro-calendar',
  linkedBiasPath: '/app/market-bias',
  linkedReportsPath: '/app/reports',
  linkedNewsPath: '/app/news?eventFamily=US%20CPI',
  horizonTag: 'next_7d',
  hoursToEvent: 48,
  whyItMatters: 'Fallback macro catalyst row for CPI-linked rates repricing.',
  geoboardModes: ['STANDARD', 'LIQUIDITY'],
  relatedNewsClusterIds: [],
  relatedNewsIds: [],
  sourceMeta: FALLBACK_SOURCE,
  ranking: rank(0.64, 0.7, 0.9, 0.5),
 },
]

export const FALLBACK_CENTRAL_BANKS: CentralBank[] = [
 {
  id: 'fed',
  name: 'FED',
  lat: 38.9,
  lon: -77,
  rate: '5.25%',
  nextMeeting: '2026-05-06',
  bias: 'DATA DEPENDENT',
  signal: 'USD LIQUIDITY TIGHT',
  liquidityWeight: 100,
  country: 'United States',
  countryCode: 'US',
  regionCode: 'NA',
  regionGroup: 'North America',
  linkedEventId: null,
  linkedEventSlug: null,
  linkedEventPath: '/app/macro-calendar',
  linkedNewsPath: '/app/news?topic=Central%20banks',
  linkedReactionPath: '/app/live-reactions',
  linkedBiasPath: '/app/market-bias',
  relatedAssets: ['DXY', 'US10Y', 'SPX', 'XAU'],
  relatedNewsClusterIds: [],
  whyItMatters: 'Curated static central bank node with fallback context.',
  geoboardModes: ['STANDARD', 'LIQUIDITY', 'CENT.BANKS'],
  sourceMeta: { ...FALLBACK_SOURCE, sourceType: 'static', mode: 'static', note: 'Curated static central bank layer.' },
  ranking: rank(0.55, 0.34, 0.85, 0.58),
 },
]

export const FALLBACK_TRADE_ROUTES: TradeRoute[] = [
 {
  id: 'hormuz',
  name: 'STRAIT OF HORMUZ',
  label: 'HORMUZ // 20% OIL',
  path: [[56.3, 26.6], [57, 24.5], [58.5, 22]],
  status: 'SHIPPING RISK ELEVATED',
  volume: '20% GLOBAL OIL',
  riskLevel: 'HIGH',
  impact: ['OIL', 'DXY', 'XAU'],
  lat: 24.5,
  lon: 57,
  regionCode: 'MENA',
  regionGroup: 'Middle East',
  linkedGeoEventIds: ['geo-fallback-hormuz'],
  relatedNewsClusterIds: [],
  linkedNewsPath: '/app/news?asset=OIL',
  linkedAlertsPath: '/app/alerts',
  whyItMatters: 'Curated chokepoint route with fallback event linkage.',
  geoboardModes: ['STANDARD', 'RISK'],
  sourceMeta: { ...FALLBACK_SOURCE, sourceType: 'static', mode: 'static', note: 'Curated static trade route layer.' },
  ranking: rank(0.6, 0.78, 0.86, 0.54),
 },
]

export const FALLBACK_REGIME_ZONES: RegimeZone[] = [
 {
  id: 'USA',
  label: 'USA',
  flag: 'US',
  regime: 'NEUTRAL',
  confidence: 62,
  center: [-98, 38],
  zoom: 2.7,
  sourceMeta: { ...FALLBACK_SOURCE, sourceType: 'derived', mode: 'derived', note: 'Derived regime fallback overlay.' },
  relatedAssets: ['SPX', 'DXY', 'US10Y'],
  whyItMatters: 'Derived regional risk context fallback.',
  geoboardModes: ['STANDARD', 'LIQUIDITY'],
 },
]

function buildFallbackFeed(): FeedItem[] {
 const geo = FALLBACK_GEO_EVENTS.map(function (item) {
  return {
   id: 'feed-geo-' + item.id,
   feedType: 'GEO_RISK' as const,
   title: item.title,
   subtitle: item.classification + ' / ' + item.country,
   time: item.date,
   impactLine: item.affectedAssets.join(' / '),
   whyItMatters: item.whyItMatters,
   lat: item.lat,
   lon: item.lon,
   sourceId: item.id,
   sourceLayer: 'geo' as const,
   regionCode: item.regionCode,
   regionGroup: item.regionGroup,
   linkedEventId: null,
   linkedEventSlug: null,
   relatedNewsClusterIds: item.relatedNewsClusterIds,
   relatedNewsIds: item.relatedNewsIds,
   linkedAssetSymbols: item.affectedAssets,
   tags: [item.classification, item.sourceMeta.sourceType],
   geoboardModes: item.geoboardModes,
   links: { calendar: '/app/macro-calendar', news: '/app/news', reactions: '/app/live-reactions', bias: '/app/market-bias', reports: '/app/reports', watchlists: '/app/watchlists', alerts: '/app/alerts', source: item.url },
   sourceMeta: item.sourceMeta,
   ranking: item.ranking,
  }
 })
 return geo
}

export const FALLBACK_GEOBOARD_PAYLOAD: GeoboardPayload = {
 generatedAt: '2026-04-08T06:00:00+00:00',
 modeState: {
  activeMode: 'STANDARD',
  availableModes: ['STANDARD', 'RISK', 'LIQUIDITY', 'CENT.BANKS'],
  fallback: true,
  sourceHonesty: 'Fallback continuity mode. Discovery rows are not live-confirmed intelligence.',
 },
 sourceStatus: [
  { layer: 'geo', state: 'fallback', sourceType: 'fallback', mode: 'fallback', detail: 'GDELT unavailable; serving fallback rows.' },
  { layer: 'macro', state: 'fallback', sourceType: 'fallback', mode: 'fallback', detail: 'Macro DB projection unavailable; serving fallback rows.' },
  { layer: 'cb', state: 'static', sourceType: 'static', mode: 'static', detail: 'Curated static central bank layer.' },
  { layer: 'trade', state: 'static', sourceType: 'static', mode: 'static', detail: 'Curated static trade-route layer.' },
  { layer: 'regime', state: 'derived', sourceType: 'derived', mode: 'derived', detail: 'Derived regime overlay fallback.' },
  { layer: 'feed', state: 'fallback', sourceType: 'derived', mode: 'derived', detail: 'Feed assembled from fallback/static/derived rows.' },
 ],
 geoEvents: FALLBACK_GEO_EVENTS,
 macroEvents: FALLBACK_MACRO_EVENTS,
 centralBanks: FALLBACK_CENTRAL_BANKS,
 tradeRoutes: FALLBACK_TRADE_ROUTES,
 regimeZones: FALLBACK_REGIME_ZONES,
 feed: buildFallbackFeed(),
 summary: {
  totalFeedItems: buildFallbackFeed().length,
  geoSignals: FALLBACK_GEO_EVENTS.length,
  macroCatalysts: FALLBACK_MACRO_EVENTS.length,
  centralBanks: FALLBACK_CENTRAL_BANKS.length,
  tradeRoutes: FALLBACK_TRADE_ROUTES.length,
  regimeZones: FALLBACK_REGIME_ZONES.length,
  watchlistSymbols: 0,
  activeAlerts: 0,
  fallbackLayers: 3,
 },
}
